### ISSUE TITLE
Python Coverage package not showing up in Sublime Package Control

### ISSUE THREAD

**Issue by RobBednark** [davisagli/SublimePythonCoverage#15]
When I search for "Python Coverage" in Sublime Package Control, it does not show any packages.  See attached screenshots.

"python co" shows some packages, but not Python Coverage:

<img width="485" alt="screen shot 2015-10-27 at 10 45 30 am" src="https://cloud.githubusercontent.com/assets/1076883/10767135/fd938002-7c97-11e5-9f6c-7e33141b3c49.png">

"python cov" shows no matching packages:

<img width="489" alt="screen shot 2015-10-27 at 10 45 39 am" src="https://cloud.githubusercontent.com/assets/1076883/10767134/fd92b514-7c97-11e5-8271-c480a926f348.png">

"coverage" shows other packages:

<img width="489" alt="screen shot 2015-10-27 at 10 45 56 am" src="https://cloud.githubusercontent.com/assets/1076883/10767136/fd95e1d0-7c97-11e5-9c71-fbbec1d4812c.png">

**Comment by davisagli** [comment]
I'm no longer maintaining this package. I'm using this one instead: https://packagecontrol.io/packages/PyCover

**Comment by RobBednark** [comment]
Super -- thanks @davisagli !
