### ISSUE TITLE
Run coverage directly from ST2 without using nose or pytest ?

### ISSUE THREAD

**Issue by bizoo** [davisagli/SublimePythonCoverage#6]
Is it possible to add a command to run coverage.py and generate .coverage file directly from ST2 without using nose or pytest ?

**Comment by davisagli** [comment]
You mean to run the .py file that is open with coverage analysis instead of running a test suite? Sure, it's possible. I don't think I understand why that would be useful though...

**Comment by bizoo** [comment]
I must confess that I never used coverage.py and don't know how it works...
When you have a Python script (that you want to run from Shell) that use a few external module, could you run coverage on the Python script only or do you have to include the external module ?

**Comment by davisagli** [comment]
Well the idea with coverage is you run your test suite, and coverage analyzes which lines of your code were run, so that you can identify code that isn't tested yet. So it doesn't make much sense to run apart from a test runner (or at least it's less obviously useful that way).

**Comment by bizoo** [comment]
Yes, you're right, not a very useful feature.
Thanks for your answer and your time.
