### ISSUE TITLE
Lines always highlighted, even after 100% coverage

### ISSUE THREAD

**Issue by echohack** [davisagli/SublimePythonCoverage#8]
After running tests and achieving coverage, none of the lines of Sublime Text will unhighlight. :(

It appears to be an issues with "show_python_coverage" because even when I manually run the command, Sublime Text doesn't know what command that is.

**Comment by niclas-ahden** [comment]
I just sent a pull request which might fix this issue.

**Comment by echohack** [comment]
Edit: After some more testing, I believe this is a conflict issue between Pylinter and SublimePythonCoverage. Now I'm interested if this happens with SublimeLinter (another common lint in Sublime Text).

Edit 2: SublimeLinter does not cause these issues. So I believe Pylinter is unique in its conflict.

Pylinter disabled:
![coverage2](https://f.cloud.github.com/assets/3253989/62559/6e45f742-5d30-11e2-9780-d57bc7c98c41.PNG)

Pylinter enabled:
![coverage](https://f.cloud.github.com/assets/3253989/62554/93e846d6-5d2f-11e2-97a8-db76cffc3620.PNG)
